package tech_world.dao;
// Generated 31/10/2018 04:56:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bodega generated by hbm2java
 */
public class Bodega  implements java.io.Serializable {


     private Integer bodegaCod;
     private Pais pais;
     private String bodegaNombre;
     private String bodegaDireccion;
     private String bodegaTelefono;
     private Set ordenIngresos = new HashSet(0);
     private Set sucursalBodegas = new HashSet(0);
     private Set productoBodegas = new HashSet(0);

    public Bodega() {
    }

	
    public Bodega(Pais pais) {
        this.pais = pais;
    }
    public Bodega(Pais pais, String bodegaNombre, String bodegaDireccion, String bodegaTelefono, Set ordenIngresos, Set sucursalBodegas, Set productoBodegas) {
       this.pais = pais;
       this.bodegaNombre = bodegaNombre;
       this.bodegaDireccion = bodegaDireccion;
       this.bodegaTelefono = bodegaTelefono;
       this.ordenIngresos = ordenIngresos;
       this.sucursalBodegas = sucursalBodegas;
       this.productoBodegas = productoBodegas;
    }
   
    public Integer getBodegaCod() {
        return this.bodegaCod;
    }
    
    public void setBodegaCod(Integer bodegaCod) {
        this.bodegaCod = bodegaCod;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getBodegaNombre() {
        return this.bodegaNombre;
    }
    
    public void setBodegaNombre(String bodegaNombre) {
        this.bodegaNombre = bodegaNombre;
    }
    public String getBodegaDireccion() {
        return this.bodegaDireccion;
    }
    
    public void setBodegaDireccion(String bodegaDireccion) {
        this.bodegaDireccion = bodegaDireccion;
    }
    public String getBodegaTelefono() {
        return this.bodegaTelefono;
    }
    
    public void setBodegaTelefono(String bodegaTelefono) {
        this.bodegaTelefono = bodegaTelefono;
    }
    public Set getOrdenIngresos() {
        return this.ordenIngresos;
    }
    
    public void setOrdenIngresos(Set ordenIngresos) {
        this.ordenIngresos = ordenIngresos;
    }
    public Set getSucursalBodegas() {
        return this.sucursalBodegas;
    }
    
    public void setSucursalBodegas(Set sucursalBodegas) {
        this.sucursalBodegas = sucursalBodegas;
    }
    public Set getProductoBodegas() {
        return this.productoBodegas;
    }
    
    public void setProductoBodegas(Set productoBodegas) {
        this.productoBodegas = productoBodegas;
    }




}


