package tech_world.dao;
// Generated 31/10/2018 08:33:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer categoriaCod;
     private String categoriaDescripcion;
     private Set productos = new HashSet(0);

    public Categoria() {
    }

    public Categoria(String categoriaDescripcion, Set productos) {
       this.categoriaDescripcion = categoriaDescripcion;
       this.productos = productos;
    }
   
    public Integer getCategoriaCod() {
        return this.categoriaCod;
    }
    
    public void setCategoriaCod(Integer categoriaCod) {
        this.categoriaCod = categoriaCod;
    }
    public String getCategoriaDescripcion() {
        return this.categoriaDescripcion;
    }
    
    public void setCategoriaDescripcion(String categoriaDescripcion) {
        this.categoriaDescripcion = categoriaDescripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


