package tech_world.dao;
// Generated 31/10/2018 08:33:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer clienteCod;
     private String clienteNombre;
     private String clienteApellido;
     private Long clienteDpi;
     private String clienteNick;
     private String clientePass;
     private String clienteEmail;
     private Set pedidos = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String clienteNombre, String clienteApellido, Long clienteDpi, String clienteNick, String clientePass, String clienteEmail, Set pedidos) {
       this.clienteNombre = clienteNombre;
       this.clienteApellido = clienteApellido;
       this.clienteDpi = clienteDpi;
       this.clienteNick = clienteNick;
       this.clientePass = clientePass;
       this.clienteEmail = clienteEmail;
       this.pedidos = pedidos;
    }
   
    public Integer getClienteCod() {
        return this.clienteCod;
    }
    
    public void setClienteCod(Integer clienteCod) {
        this.clienteCod = clienteCod;
    }
    public String getClienteNombre() {
        return this.clienteNombre;
    }
    
    public void setClienteNombre(String clienteNombre) {
        this.clienteNombre = clienteNombre;
    }
    public String getClienteApellido() {
        return this.clienteApellido;
    }
    
    public void setClienteApellido(String clienteApellido) {
        this.clienteApellido = clienteApellido;
    }
    public Long getClienteDpi() {
        return this.clienteDpi;
    }
    
    public void setClienteDpi(Long clienteDpi) {
        this.clienteDpi = clienteDpi;
    }
    public String getClienteNick() {
        return this.clienteNick;
    }
    
    public void setClienteNick(String clienteNick) {
        this.clienteNick = clienteNick;
    }
    public String getClientePass() {
        return this.clientePass;
    }
    
    public void setClientePass(String clientePass) {
        this.clientePass = clientePass;
    }
    public String getClienteEmail() {
        return this.clienteEmail;
    }
    
    public void setClienteEmail(String clienteEmail) {
        this.clienteEmail = clienteEmail;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


