package tech_world.dao;
// Generated 31/10/2018 08:33:28 PM by Hibernate Tools 4.3.1



/**
 * DetalleIngreso generated by hbm2java
 */
public class DetalleIngreso  implements java.io.Serializable {


     private Integer diCod;
     private OrdenIngreso ordenIngreso;
     private Producto producto;
     private Integer diCantidad;
     private String diVariacion;

    public DetalleIngreso() {
    }

	
    public DetalleIngreso(OrdenIngreso ordenIngreso, Producto producto) {
        this.ordenIngreso = ordenIngreso;
        this.producto = producto;
    }
    public DetalleIngreso(OrdenIngreso ordenIngreso, Producto producto, Integer diCantidad, String diVariacion) {
       this.ordenIngreso = ordenIngreso;
       this.producto = producto;
       this.diCantidad = diCantidad;
       this.diVariacion = diVariacion;
    }
   
    public Integer getDiCod() {
        return this.diCod;
    }
    
    public void setDiCod(Integer diCod) {
        this.diCod = diCod;
    }
    public OrdenIngreso getOrdenIngreso() {
        return this.ordenIngreso;
    }
    
    public void setOrdenIngreso(OrdenIngreso ordenIngreso) {
        this.ordenIngreso = ordenIngreso;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getDiCantidad() {
        return this.diCantidad;
    }
    
    public void setDiCantidad(Integer diCantidad) {
        this.diCantidad = diCantidad;
    }
    public String getDiVariacion() {
        return this.diVariacion;
    }
    
    public void setDiVariacion(String diVariacion) {
        this.diVariacion = diVariacion;
    }




}


