package tech_world.dao;
// Generated 31/10/2018 08:33:28 PM by Hibernate Tools 4.3.1



/**
 * DetalleOrden generated by hbm2java
 */
public class DetalleOrden  implements java.io.Serializable {


     private Integer doCod;
     private OrdenCompra ordenCompra;
     private Producto producto;
     private Integer doCantidad;
     private Float doPrecio;

    public DetalleOrden() {
    }

	
    public DetalleOrden(OrdenCompra ordenCompra, Producto producto) {
        this.ordenCompra = ordenCompra;
        this.producto = producto;
    }
    public DetalleOrden(OrdenCompra ordenCompra, Producto producto, Integer doCantidad, Float doPrecio) {
       this.ordenCompra = ordenCompra;
       this.producto = producto;
       this.doCantidad = doCantidad;
       this.doPrecio = doPrecio;
    }
   
    public Integer getDoCod() {
        return this.doCod;
    }
    
    public void setDoCod(Integer doCod) {
        this.doCod = doCod;
    }
    public OrdenCompra getOrdenCompra() {
        return this.ordenCompra;
    }
    
    public void setOrdenCompra(OrdenCompra ordenCompra) {
        this.ordenCompra = ordenCompra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getDoCantidad() {
        return this.doCantidad;
    }
    
    public void setDoCantidad(Integer doCantidad) {
        this.doCantidad = doCantidad;
    }
    public Float getDoPrecio() {
        return this.doPrecio;
    }
    
    public void setDoPrecio(Float doPrecio) {
        this.doPrecio = doPrecio;
    }




}


