package tech_world.dao;
// Generated 31/10/2018 08:33:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer empleadoCod;
     private TipoEmpleado tipoEmpleado;
     private int empleadoSucursalCod;
     private String empleadoNombre;
     private String empleadoApellido;
     private Float empleadoSalario;
     private Set ordenCompras = new HashSet(0);
     private Set pedidos = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(TipoEmpleado tipoEmpleado, int empleadoSucursalCod) {
        this.tipoEmpleado = tipoEmpleado;
        this.empleadoSucursalCod = empleadoSucursalCod;
    }
    public Empleado(TipoEmpleado tipoEmpleado, int empleadoSucursalCod, String empleadoNombre, String empleadoApellido, Float empleadoSalario, Set ordenCompras, Set pedidos) {
       this.tipoEmpleado = tipoEmpleado;
       this.empleadoSucursalCod = empleadoSucursalCod;
       this.empleadoNombre = empleadoNombre;
       this.empleadoApellido = empleadoApellido;
       this.empleadoSalario = empleadoSalario;
       this.ordenCompras = ordenCompras;
       this.pedidos = pedidos;
    }
   
    public Integer getEmpleadoCod() {
        return this.empleadoCod;
    }
    
    public void setEmpleadoCod(Integer empleadoCod) {
        this.empleadoCod = empleadoCod;
    }
    public TipoEmpleado getTipoEmpleado() {
        return this.tipoEmpleado;
    }
    
    public void setTipoEmpleado(TipoEmpleado tipoEmpleado) {
        this.tipoEmpleado = tipoEmpleado;
    }
    public int getEmpleadoSucursalCod() {
        return this.empleadoSucursalCod;
    }
    
    public void setEmpleadoSucursalCod(int empleadoSucursalCod) {
        this.empleadoSucursalCod = empleadoSucursalCod;
    }
    public String getEmpleadoNombre() {
        return this.empleadoNombre;
    }
    
    public void setEmpleadoNombre(String empleadoNombre) {
        this.empleadoNombre = empleadoNombre;
    }
    public String getEmpleadoApellido() {
        return this.empleadoApellido;
    }
    
    public void setEmpleadoApellido(String empleadoApellido) {
        this.empleadoApellido = empleadoApellido;
    }
    public Float getEmpleadoSalario() {
        return this.empleadoSalario;
    }
    
    public void setEmpleadoSalario(Float empleadoSalario) {
        this.empleadoSalario = empleadoSalario;
    }
    public Set getOrdenCompras() {
        return this.ordenCompras;
    }
    
    public void setOrdenCompras(Set ordenCompras) {
        this.ordenCompras = ordenCompras;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


