package tech_world.dao;
// Generated 31/10/2018 08:33:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcion generated by hbm2java
 */
public class Funcion  implements java.io.Serializable {


     private Integer funcionCod;
     private String funcionDescripcion;
     private Set usuarios = new HashSet(0);

    public Funcion() {
    }

    public Funcion(String funcionDescripcion, Set usuarios) {
       this.funcionDescripcion = funcionDescripcion;
       this.usuarios = usuarios;
    }
   
    public Integer getFuncionCod() {
        return this.funcionCod;
    }
    
    public void setFuncionCod(Integer funcionCod) {
        this.funcionCod = funcionCod;
    }
    public String getFuncionDescripcion() {
        return this.funcionDescripcion;
    }
    
    public void setFuncionDescripcion(String funcionDescripcion) {
        this.funcionDescripcion = funcionDescripcion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


