package tech_world.dao;
// Generated 31/10/2018 08:33:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenCompra generated by hbm2java
 */
public class OrdenCompra  implements java.io.Serializable {


     private Integer ocCod;
     private Empleado empleado;
     private Proveedor proveedor;
     private Date ocFecha;
     private Float ocPreciototal;
     private Set detalleOrdens = new HashSet(0);

    public OrdenCompra() {
    }

	
    public OrdenCompra(Empleado empleado, Proveedor proveedor) {
        this.empleado = empleado;
        this.proveedor = proveedor;
    }
    public OrdenCompra(Empleado empleado, Proveedor proveedor, Date ocFecha, Float ocPreciototal, Set detalleOrdens) {
       this.empleado = empleado;
       this.proveedor = proveedor;
       this.ocFecha = ocFecha;
       this.ocPreciototal = ocPreciototal;
       this.detalleOrdens = detalleOrdens;
    }
   
    public Integer getOcCod() {
        return this.ocCod;
    }
    
    public void setOcCod(Integer ocCod) {
        this.ocCod = ocCod;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getOcFecha() {
        return this.ocFecha;
    }
    
    public void setOcFecha(Date ocFecha) {
        this.ocFecha = ocFecha;
    }
    public Float getOcPreciototal() {
        return this.ocPreciototal;
    }
    
    public void setOcPreciototal(Float ocPreciototal) {
        this.ocPreciototal = ocPreciototal;
    }
    public Set getDetalleOrdens() {
        return this.detalleOrdens;
    }
    
    public void setDetalleOrdens(Set detalleOrdens) {
        this.detalleOrdens = detalleOrdens;
    }




}


