package tech_world.dao;
// Generated 29/10/2018 09:18:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenIngreso generated by hbm2java
 */
public class OrdenIngreso  implements java.io.Serializable {


     private Integer oiCod;
     private Bodega bodega;
     private Date oiFechaingreso;
     private Set detalleIngresos = new HashSet(0);

    public OrdenIngreso() {
    }

	
    public OrdenIngreso(Bodega bodega) {
        this.bodega = bodega;
    }
    public OrdenIngreso(Bodega bodega, Date oiFechaingreso, Set detalleIngresos) {
       this.bodega = bodega;
       this.oiFechaingreso = oiFechaingreso;
       this.detalleIngresos = detalleIngresos;
    }
   
    public Integer getOiCod() {
        return this.oiCod;
    }
    
    public void setOiCod(Integer oiCod) {
        this.oiCod = oiCod;
    }
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }
    public Date getOiFechaingreso() {
        return this.oiFechaingreso;
    }
    
    public void setOiFechaingreso(Date oiFechaingreso) {
        this.oiFechaingreso = oiFechaingreso;
    }
    public Set getDetalleIngresos() {
        return this.detalleIngresos;
    }
    
    public void setDetalleIngresos(Set detalleIngresos) {
        this.detalleIngresos = detalleIngresos;
    }




}


