package tech_world.dao;
// Generated 31/10/2018 08:33:28 PM by Hibernate Tools 4.3.1



/**
 * ProductoProveedorId generated by hbm2java
 */
public class ProductoProveedorId  implements java.io.Serializable {


     private int ppProductoCod;
     private int ppProveedorCod;

    public ProductoProveedorId() {
    }

    public ProductoProveedorId(int ppProductoCod, int ppProveedorCod) {
       this.ppProductoCod = ppProductoCod;
       this.ppProveedorCod = ppProveedorCod;
    }
   
    public int getPpProductoCod() {
        return this.ppProductoCod;
    }
    
    public void setPpProductoCod(int ppProductoCod) {
        this.ppProductoCod = ppProductoCod;
    }
    public int getPpProveedorCod() {
        return this.ppProveedorCod;
    }
    
    public void setPpProveedorCod(int ppProveedorCod) {
        this.ppProveedorCod = ppProveedorCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductoProveedorId) ) return false;
		 ProductoProveedorId castOther = ( ProductoProveedorId ) other; 
         
		 return (this.getPpProductoCod()==castOther.getPpProductoCod())
 && (this.getPpProveedorCod()==castOther.getPpProveedorCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPpProductoCod();
         result = 37 * result + this.getPpProveedorCod();
         return result;
   }   


}


