package tech_world.dao;
// Generated 29/10/2018 09:18:53 PM by Hibernate Tools 4.3.1



/**
 * ProductoBodega generated by hbm2java
 */
public class ProductoBodega  implements java.io.Serializable {


     private Integer productoBodega;
     private Bodega bodega;
     private Producto producto;
     private Integer pbCantidad;

    public ProductoBodega() {
    }

	
    public ProductoBodega(Bodega bodega, Producto producto) {
        this.bodega = bodega;
        this.producto = producto;
    }
    public ProductoBodega(Bodega bodega, Producto producto, Integer pbCantidad) {
       this.bodega = bodega;
       this.producto = producto;
       this.pbCantidad = pbCantidad;
    }
   
    public Integer getProductoBodega() {
        return this.productoBodega;
    }
    
    public void setProductoBodega(Integer productoBodega) {
        this.productoBodega = productoBodega;
    }
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getPbCantidad() {
        return this.pbCantidad;
    }
    
    public void setPbCantidad(Integer pbCantidad) {
        this.pbCantidad = pbCantidad;
    }




}


