package tech_world.dao;
// Generated 22/10/2018 02:49:58 PM by Hibernate Tools 4.3.1



/**
 * ProductoProveedor generated by hbm2java
 */
public class ProductoProveedor  implements java.io.Serializable {


     private Integer ppCod;
     private Producto producto;
     private Proveedor proveedor;

    public ProductoProveedor() {
    }

    public ProductoProveedor(Producto producto, Proveedor proveedor) {
       this.producto = producto;
       this.proveedor = proveedor;
    }
   
    public Integer getPpCod() {
        return this.ppCod;
    }
    
    public void setPpCod(Integer ppCod) {
        this.ppCod = ppCod;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }




}


