package tech_world.dao;
// Generated 1/11/2018 06:26:43 PM by Hibernate Tools 4.3.1



/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer proveedorCod;
     private Pais pais;
     private String proveedorNombre;
     private String proveedorTelefono;

    public Proveedor() {
    }

	
    public Proveedor(Pais pais) {
        this.pais = pais;
    }
    public Proveedor(Pais pais, String proveedorNombre, String proveedorTelefono) {
       this.pais = pais;
       this.proveedorNombre = proveedorNombre;
       this.proveedorTelefono = proveedorTelefono;
    }
   
    public Integer getProveedorCod() {
        return this.proveedorCod;
    }
    
    public void setProveedorCod(Integer proveedorCod) {
        this.proveedorCod = proveedorCod;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getProveedorNombre() {
        return this.proveedorNombre;
    }
    
    public void setProveedorNombre(String proveedorNombre) {
        this.proveedorNombre = proveedorNombre;
    }
    public String getProveedorTelefono() {
        return this.proveedorTelefono;
    }
    
    public void setProveedorTelefono(String proveedorTelefono) {
        this.proveedorTelefono = proveedorTelefono;
    }




}


