package tech_world.dao;
// Generated 31/10/2018 08:33:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer proveedorCod;
     private Pais pais;
     private String proveedorNombre;
     private Integer proveedorTelefono;
     private Set productoProveedors = new HashSet(0);
     private Set ordenCompras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(Pais pais) {
        this.pais = pais;
    }
    public Proveedor(Pais pais, String proveedorNombre, Integer proveedorTelefono, Set productoProveedors, Set ordenCompras) {
       this.pais = pais;
       this.proveedorNombre = proveedorNombre;
       this.proveedorTelefono = proveedorTelefono;
       this.productoProveedors = productoProveedors;
       this.ordenCompras = ordenCompras;
    }
   
    public Integer getProveedorCod() {
        return this.proveedorCod;
    }
    
    public void setProveedorCod(Integer proveedorCod) {
        this.proveedorCod = proveedorCod;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getProveedorNombre() {
        return this.proveedorNombre;
    }
    
    public void setProveedorNombre(String proveedorNombre) {
        this.proveedorNombre = proveedorNombre;
    }
    public Integer getProveedorTelefono() {
        return this.proveedorTelefono;
    }
    
    public void setProveedorTelefono(Integer proveedorTelefono) {
        this.proveedorTelefono = proveedorTelefono;
    }
    public Set getProductoProveedors() {
        return this.productoProveedors;
    }
    
    public void setProductoProveedors(Set productoProveedors) {
        this.productoProveedors = productoProveedors;
    }
    public Set getOrdenCompras() {
        return this.ordenCompras;
    }
    
    public void setOrdenCompras(Set ordenCompras) {
        this.ordenCompras = ordenCompras;
    }




}


