package tech_world.dao;
// Generated 22/10/2018 02:49:58 PM by Hibernate Tools 4.3.1



/**
 * SucursalBodega generated by hbm2java
 */
public class SucursalBodega  implements java.io.Serializable {


     private Integer sbCod;
     private Bodega bodega;
     private Producto producto;
     private Sucursal sucursal;
     private Integer sbCantidad;

    public SucursalBodega() {
    }

	
    public SucursalBodega(Bodega bodega, Producto producto, Sucursal sucursal) {
        this.bodega = bodega;
        this.producto = producto;
        this.sucursal = sucursal;
    }
    public SucursalBodega(Bodega bodega, Producto producto, Sucursal sucursal, Integer sbCantidad) {
       this.bodega = bodega;
       this.producto = producto;
       this.sucursal = sucursal;
       this.sbCantidad = sbCantidad;
    }
   
    public Integer getSbCod() {
        return this.sbCod;
    }
    
    public void setSbCod(Integer sbCod) {
        this.sbCod = sbCod;
    }
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Integer getSbCantidad() {
        return this.sbCantidad;
    }
    
    public void setSbCantidad(Integer sbCantidad) {
        this.sbCantidad = sbCantidad;
    }




}


