package tech_world.dao;
// Generated 29/10/2018 09:18:53 PM by Hibernate Tools 4.3.1



/**
 * SucursalBodega generated by hbm2java
 */
public class SucursalBodega  implements java.io.Serializable {


     private Integer sucursalBodega;
     private Bodega bodega;
     private Sucursal sucursal;
     private int sbProductoCod;
     private Integer sbCantidad;

    public SucursalBodega() {
    }

	
    public SucursalBodega(Bodega bodega, Sucursal sucursal, int sbProductoCod) {
        this.bodega = bodega;
        this.sucursal = sucursal;
        this.sbProductoCod = sbProductoCod;
    }
    public SucursalBodega(Bodega bodega, Sucursal sucursal, int sbProductoCod, Integer sbCantidad) {
       this.bodega = bodega;
       this.sucursal = sucursal;
       this.sbProductoCod = sbProductoCod;
       this.sbCantidad = sbCantidad;
    }
   
    public Integer getSucursalBodega() {
        return this.sucursalBodega;
    }
    
    public void setSucursalBodega(Integer sucursalBodega) {
        this.sucursalBodega = sucursalBodega;
    }
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public int getSbProductoCod() {
        return this.sbProductoCod;
    }
    
    public void setSbProductoCod(int sbProductoCod) {
        this.sbProductoCod = sbProductoCod;
    }
    public Integer getSbCantidad() {
        return this.sbCantidad;
    }
    
    public void setSbCantidad(Integer sbCantidad) {
        this.sbCantidad = sbCantidad;
    }




}


