package tech_world.dao;
// Generated 31/10/2018 08:33:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoEmpleado generated by hbm2java
 */
public class TipoEmpleado  implements java.io.Serializable {


     private Integer tipoCod;
     private String tipoDescripcion;
     private Set empleados = new HashSet(0);

    public TipoEmpleado() {
    }

    public TipoEmpleado(String tipoDescripcion, Set empleados) {
       this.tipoDescripcion = tipoDescripcion;
       this.empleados = empleados;
    }
   
    public Integer getTipoCod() {
        return this.tipoCod;
    }
    
    public void setTipoCod(Integer tipoCod) {
        this.tipoCod = tipoCod;
    }
    public String getTipoDescripcion() {
        return this.tipoDescripcion;
    }
    
    public void setTipoDescripcion(String tipoDescripcion) {
        this.tipoDescripcion = tipoDescripcion;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


