package tech_world.dao;
// Generated 22/10/2018 02:49:58 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer usuarioCod;
     private Funcion funcion;
     private String usuarioNombre;
     private String usuarioApellido;
     private String usuarioNick;
     private String usuarioPass;

    public Usuario() {
    }

	
    public Usuario(Funcion funcion) {
        this.funcion = funcion;
    }
    public Usuario(Funcion funcion, String usuarioNombre, String usuarioApellido, String usuarioNick, String usuarioPass) {
       this.funcion = funcion;
       this.usuarioNombre = usuarioNombre;
       this.usuarioApellido = usuarioApellido;
       this.usuarioNick = usuarioNick;
       this.usuarioPass = usuarioPass;
    }
   
    public Integer getUsuarioCod() {
        return this.usuarioCod;
    }
    
    public void setUsuarioCod(Integer usuarioCod) {
        this.usuarioCod = usuarioCod;
    }
    public Funcion getFuncion() {
        return this.funcion;
    }
    
    public void setFuncion(Funcion funcion) {
        this.funcion = funcion;
    }
    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }
    
    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }
    public String getUsuarioApellido() {
        return this.usuarioApellido;
    }
    
    public void setUsuarioApellido(String usuarioApellido) {
        this.usuarioApellido = usuarioApellido;
    }
    public String getUsuarioNick() {
        return this.usuarioNick;
    }
    
    public void setUsuarioNick(String usuarioNick) {
        this.usuarioNick = usuarioNick;
    }
    public String getUsuarioPass() {
        return this.usuarioPass;
    }
    
    public void setUsuarioPass(String usuarioPass) {
        this.usuarioPass = usuarioPass;
    }




}


